extends SceneTree
## Rebuild the synthetic .bzn fixtures for test_bz_bzn.gd and friends.
##
##   godot --headless --path . -s tests/gd/fixtures/bzn/make_fixtures.gd
##
## The fixtures are committed, so this only needs running when the intended
## content changes. It is here so that content is written down as source
## rather than living only inside two opaque binaries.
##
## Nothing in this file is game data: the header, both objects and the tail are
## hand-authored below, modelled on the shape of a stock ASCII BZN but sharing
## none of its content. "synthmap" is not a real terrain.
##
## `mutated_pos.bzn` is written from its own hand-authored text, NOT by calling
## `set_position` on the geyser. That matters: `test_bz_bzn.gd` asserts that
## `set_position(333.125, 44.5, 555.875)` reproduces this file byte for byte,
## and a golden generated by the routine under test could not fail that.

const DIR := "res://tests/gd/fixtures/bzn"

const HEADER := """version [1] =
2016
binarySave [1] =
false
msn_filename = synthmap.bzn
seq_count [1] =
2
missionSave [1] =
true
TerrainName = synthmap
size [1] =
2"""

const TAIL := """[AiMission]
[AOIs]
size [1] =
0
[AiPaths]
count [1] =
0"""

## seqno 0, team 1, the user's own craft. obj_addr runs from 1 in file order
## or BznFile.validate() complains.
const PLAYER := """[GameObject]
PrjID [1] =
player
seqno [1] =
0
pos [1] =
  x [1] =
640
  y [1] =
10
  z [1] =
640
team [1] =
1
label = synthmap0_player
isUser [1] =
1
obj_addr = 00000001
transform [1] =
  right_x [1] =
1
  right_y [1] =
0
  right_z [1] =
0
  up_x [1] =
0
  up_y [1] =
1
  up_z [1] =
0
  front_x [1] =
0
  front_y [1] =
0
  front_z [1] =
1
  posit_x [1] =
640
  posit_y [1] =
10
  posit_z [1] =
640
illumination [1] =
1
pos [1] =
  x [1] =
640
  y [1] =
10
  z [1] =
640
euler =
 mass [1] =
0
 mass_inv [1] =
1e+030
 v_mag [1] =
0
 v_mag_inv [1] =
1e+030
 I [1] =
0
 k_i [1] =
1
 v [1] =
  x [1] =
0
  y [1] =
0
  z [1] =
0
 omega [1] =
  x [1] =
0
  y [1] =
0
  z [1] =
0
 Accel [1] =
  x [1] =
0
  y [1] =
0
  z [1] =
0
seqNo [1] =
0
name = """


## The geyser, with its position spelled out in the three places set_position
## touches: both `pos` blocks and the transform's `posit_*` triple.
static func geyser(x: String, y: String, z: String) -> String:
	return """[GameObject]
PrjID [1] =
eggeizr1
seqno [1] =
1
pos [1] =
  x [1] =
{X}
  y [1] =
{Y}
  z [1] =
{Z}
team [1] =
0
label = synthmap1_geyser
isUser [1] =
0
obj_addr = 00000002
transform [1] =
  right_x [1] =
1
  right_y [1] =
0
  right_z [1] =
0
  up_x [1] =
0
  up_y [1] =
1
  up_z [1] =
0
  front_x [1] =
0
  front_y [1] =
0
  front_z [1] =
1
  posit_x [1] =
{X}
  posit_y [1] =
{Y}
  posit_z [1] =
{Z}
illumination [1] =
0
pos [1] =
  x [1] =
{X}
  y [1] =
{Y}
  z [1] =
{Z}
seqNo [1] =
1
name = """.format({"X": x, "Y": y, "Z": z})


func _initialize() -> void:
	var ok := true
	ok = _emit("untouched.bzn", geyser("100.25", "12.5", "200.75")) and ok
	# The expected result of set_position(333.125, 44.5, 555.875).
	ok = _emit("mutated_pos.bzn", geyser("333.125", "44.5", "555.875")) and ok
	quit(0 if ok else 1)


func _emit(name: String, geyser_block: String) -> bool:
	var bzn = BzBzn.BznFile.build(
		HEADER,
		[BzBzn.GameObject.from_template(PLAYER), BzBzn.GameObject.from_template(geyser_block)],
		TAIL
	)
	var problems: PackedStringArray = bzn.validate()
	if not problems.is_empty():
		printerr("%s does not validate: %s" % [name, ", ".join(problems)])
		return false
	var path: String = DIR.path_join(name)
	var wr: Dictionary = bzn.write(path)
	if not bool(wr.get("ok", false)):
		printerr("%s: write failed: %s" % [name, str(wr)])
		return false
	print("wrote %s (%d bytes)" % [path, FileAccess.get_file_as_bytes(path).size()])
	return true
